### ISSUE TITLE
Bundle with dependencies

### ISSUE THREAD

**Issue by Andonvr** [ErnstHot/TypeScript-for-Max#28]
I'm having difficulties to use a websocket server, since typescript doesn't bundle the dependencies. Here's my journey:

When I install [ws](https://www.npmjs.com/package/ws) as a dependency, import and use it, and then compile, I first get this error: 

```
$ tsc
node_modules/@types/maxmsp/index.d.ts:50:15 - error TS2300: Duplicate identifier 'Buffer'.

50 declare class Buffer {
                 ~~~~~~

  node_modules/@types/node/buffer.d.ts:616:19
    616         interface Buffer extends Uint8Array {
                          ~~~~~~
    'Buffer' was also declared here.
  node_modules/@types/node/buffer.d.ts:2299:13
    2299         var Buffer: BufferConstructor;
                     ~~~~~~
    and here.

node_modules/@types/node/buffer.d.ts:116:14 - error TS2661: Cannot export 'Buffer'. Only local declarations can be exported from a module.

116     export { Buffer };
                 ~~~~~~

node_modules/@types/node/buffer.d.ts:616:19 - error TS2300: Duplicate identifier 'Buffer'.

616         interface Buffer extends Uint8Array {
                      ~~~~~~

  node_modules/@types/maxmsp/index.d.ts:50:15
    50 declare class Buffer {
                     ~~~~~~
    'Buffer' was also declared here.

node_modules/@types/node/buffer.d.ts:2299:13 - error TS2300: Duplicate identifier 'Buffer'.

2299         var Buffer: BufferConstructor;
                 ~~~~~~

  node_modules/@types/maxmsp/index.d.ts:50:15
    50 declare class Buffer {
                     ~~~~~~
    'Buffer' was also declared here.

node_modules/@types/node/fs/promises.d.ts:56:66 - error TS2344: Type 'Buffer' does not satisfy the constraint 'ArrayBufferView'.
  Type 'Buffer' is missing the following properties from type 'BigUint64Array': BYTES_PER_ELEMENT, buffer, byteLength, byteOffset, and 26 more.

56     interface FileReadOptions<T extends NodeJS.ArrayBufferView = Buffer> {
                                                                    ~~~~~~

node_modules/@types/node/fs/promises.d.ts:218:49 - error TS2344: Type 'Buffer' does not satisfy the constraint 'ArrayBufferView'.

218         read<T extends NodeJS.ArrayBufferView = Buffer>(options?: FileReadOptions<T>): Promise<FileReadResult<T>>;
```

This I already don't really understand. Do you define your own Buffer, and it clashes with the definitions in node?
I was able to circumvent this with `"skipLibCheck": true` in the tsconfig

But then when using it in Max, I get the error:
`Javascript TypeError: ws_1.WebSocketServer is not a constructor, line 6`.

After looking inside the built files, I see that `ws` is not included. I guess that makes sense.  
But how could I bundle my code with the dependencies?  
I already tried doing some magic with Rollup, but didn't yet manage.
Do you have a solution for this?

**Comment by twhiston** [comment]
There are quite a few Max types which create duplicate definitions of DOM types unfortunately. You can use the `lib` field in your `tsconfig` to work around this, usually `"lib": ["es6"]` does the job. 

However in this case there's a more fundamental problem. These definitions are for the max [js] and [jsui] objects, those objects do not use node for their runtime. If you are using max's [node.script] object then you need to use the `maxapi` types instead of these.
